### ISSUE TITLE
SSL connection

### ISSUE THREAD

**Issue by AugustoRubio** [deStrO/eBot-CSGO#151]
It's possible ? And use other types of PHP?

**Comment by Nols1000** [comment]
You could set up a proxy to do the TLS. Something like [caddy](https://github.com/mholt/caddy) should work just fine (Keep in mind to build caddy yourself or you could break the license agreement, because to the prebuild binaries applies a diffrent license than to the source code). What do you mean with "And use other types of PHP?"?

**Comment by Augusto22xb** [comment]
Use other versions of PHP. For exemple PHP 7.0. 
I tried to use this method but it did not work: http://forum.esport-tools.net/d/319-websocket-https/3

**Comment by Nols1000** [comment]
If you want to run eBot on PHP 7.0 try it out. It's most likely not supported. So what did not work for you when trying to use ssl websockets? Please write it into the forum as the issue section is not designed to give technical support.

**Comment by zxwjoe** [comment]
Getting error 500
Internal server error
For more information:
The server encountered an internal error or misconfiguration and was unable to complete your request.

More information about this error is available in the server error_log file located in your virtual server's "logs" directory.

**Comment by zxwjoe** [comment]
[2019-05-02 16:31:26.642410] [vhost: estdc.eu] [core:alert] [pid 17123] config.c(2302): [client 185.193.60.19:51034] /data03/virt75680/domeenid/www.estdc.eu/htdocs/eBot-CSGO-Web-master/web/.htaccess: Rejecting line 1: ERROR: Options Directive can't contain 'ExecCGI' flags
