### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by adamdecaf** [deStrO/eBot-CSGO#44]
I was reading through the source recently and noticed some scary lines contained in here. Here's [an example](https://github.com/deStrO/eBot-CSGO/blob/threads/src/eBot/Match/Match.php#L132).

```php
$query = \mysql_query("SELECT * FROM `matchs` WHERE id = '" . $match_id . "'");
```

This would be able to be defeated with a `$match_id` such as `'; <insert-bad-sql>;`. Is there something I'm missing with the usage of [mysql_real_escape_string](http://php.net/manual/en/function.mysql-real-escape-string.php) or some other form of sql injection protection? I see it in [only one](https://github.com/deStrO/eBot-CSGO/blob/threads/src/eBot/Match/Player.php#L224) line in the default branch on github.

**Comment by deStrO** [comment]
Match ID doesn't need to be escaped because it can be only an integer and it's recieved from the SQL server. :)

All input/datas who can be send from outside, like players name, or even server logs need to be escaped.

And in the next eBot version, we will use PDO, so no need anymore to handle those case :)

**Comment by adamdecaf** [comment]
@deStrO Alright, I'm glad that PDO is going to be used. :dancer:
