### ISSUE TITLE
BOT does not send the right IP to the logaddresslist

### ISSUE THREAD

**Issue by udnes99** [deStrO/eBot-CSGO#67]
I will put this short;
I am hosting eBot panel + bot on my home network.

I cannot listen for the external IP, so I put the local IP (1.0.0.3 in this case). However, I am unable to use the in game commands because the eBot is sending the wrong ip through rcon for logaddresslist. If I try to listen to the public IP I get WebSocket crash.

Please help me; is there a way I can override the listen command for websockso I can put IP like 0.0.0.0 or 1.0.0.3 in bootstrap.php?

**Comment by udni** [comment]
So I have a half-decent fix for anyone having the same problem:

I went into Match.php and modified it where it sends the rcon logaddress_add and logaddress_del 
Instead of pulling it from the config, I entered the public IP string directly. So now I have local IP in my config, but external IP in Match.php in those commands.

**Comment by theantihero** [comment]
Never had your problem on my end. Could be SELinux or iptables?
