### ISSUE TITLE
End of game lag & timeouts

### ISSUE THREAD

**Issue by Existeeence** [deStrO/eBot-CSGO#81]
At the end of every match, when the CSGO server pushes the demo to my eBot server, there's a 2-10 second period of where everything lags. This is not noticeable to players unless they're attempting to type in chat, but it's very obvious to viewers on GOTV (their stream will pause for that period of time). 

The only way to prevent it from doing this is setting the gamemode to 0 0 on the launch parameters, but this creates other issues when trying to use it for competitive. 

Other people seem to be having this issue, as seen at the bottom of #78 .   
@mog54's screenshot is similar to the output for the listener server: https://cloud.githubusercontent.com/assets/17116568/14609445/1fea79d2-058a-11e6-9837-4f436b5e3274.JPG

Has anyone found a fix for this other than the one above?

**Comment by mog54** [comment]
Hi, 

like it was said on my issue, you have an time out, but the command is correctly execute.  

I had at the end of game a short freeze (1 sec) but i think it's due to the ebot and csgo server are running on VMs on my laptop.

So nothing like you. :(

your ebot is running on linux or windows? (and which version of it?)
Have you tried to simplify your server.cfg? ebot send "rcon exec server.cfg" when games ends.

Mog54

**Comment by Existeeence** [comment]
Both eBot and the CSGO server are running on linux. eBot is the latest version for both web and listener.

I've tried emptying the server.cfg and running it with no avail.

**Comment by Existeeence** [comment]
I fixed the lag for GOTV by adding a sleep timer for the stop TV record function.
It's ghetto but it's a fix for now.
