### ISSUE TITLE
add command trigger

### ISSUE THREAD

**Issue by MikkelDK** [deStrO/eBot-CSGO#94]
Hello,

Are it's possible to add command trigger on eBot-CSGO ?

Example: !pracc > it's exec of file on server
- !pracc > exec pracc.cfg

hit me up! ;)

**Comment by MikkelDK** [comment]
//Moved to pull requests

**Comment by heew** [comment]
I dont think this is something that should go into public one, but you can easily add one yourself if you want to have that if your using my master branch then edit this section https://github.com/heew/eBot-CSGO/blob/master/src/eBot/Match/Match.php#L1456

Add this after the hilighted line:
```
} elseif ($this->isCommand($message, "pracc")) {
$this->rcon->send("exec pracc.cfg");
```
After this you should be good to go.

**Comment by heew** [comment]
The reason I think it should not go in the public version is because it is a very specific need for someone (ie command X executes cfg file Y). Also it could be abused if you dont have some logic around to for example say only allow this command in warmup etc. For my `!fixwarmup` for example I restricted it to only be allowed in warmup and only allowed to be ran once per match. So I would definitely look at that logic and restrict your custom command some aswell.

**Comment by MikkelDK** [comment]
Heew: it was most to the private! :)
